"version": "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "postgresdb_container"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - fullstack
    volumes:
      - database_postgres:/data/postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    ports:
      - "5050:80"
    networks:
      - fullstack
    restart: unless-stopped
  api:
    build: .
    container_name: "golang_gin_jwt_api"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SSL_MODE: ${SSL_MODE}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack
volumes:
  database_postgres:
networks:
  fullstack:
    driver: bridge
